name: Unity Build Workflow 🔨

on:
  push:
    branches:
      - main
  pull_request: {}

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore Library cache
        uses: actions/cache@v4
        with:
          path: PacoMonkey/Library
          key: Library-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            Library-${{ runner.os }}

      - name: Activate Unity license
        uses: game-ci/unity-activate@v2
        with:
          unityLicense: ${{ secrets.UNITY_LICENSE }}

      - name: Run Unity tests
        uses: game-ci/unity-test-runner@v2
        with:
          projectPath: PacoMonkey
          testMode: all

      - name: Build project
        uses: game-ci/unity-builder@v2
        with:
          projectPath: PacoMonkey
          targetPlatform: WebGL

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: WebGL Build
          path: PacoMonkey/build/WebGL