name: Unity Build Workflow 🔨

on:
  push:
    branches:
      - main
  pull_request: {}

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Unity packages
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-$(runner.os)-$(hashFiles('**/Packages/manifest.json'))
          restore-keys: |
            Library-$(runner.os)-

      - name: Activate Unity license
        uses: game-ci/unity-activate@v2
        with:
          unityVersion: '2022.3.14f1'
          activationFile: ${{ secrets.UNITY_LICENSE }}

      - name: Build project
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: '2022.3.14f1'
          targetPlatform: WebGL

