name: Unity Build [Windows64]

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Unity Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Unity
        run: |
          sudo apt-get update
          sudo apt-get install -y lib32gcc-s1 lib32stdc++6
          wget https://download.unity3d.com/download_unity/eff2de9070d8/LinuxEditorInstaller/Unity-2022.3.14f1.tar.xz
          sudo mkdir -p /opt/Unity
          sudo tar -xf Unity-2022.3.14f1.tar.xz -C /opt/Unity --strip-components=1

      - name: Run Unity Build
        run: |
          /opt/Unity/Editor/Unity \
          -batchmode \
          -nographics \
          -quit \
          -projectPath . \
          -buildTarget StandaloneWindows64 \
          -buildOutput build/PacoMonkeyBuild.exe

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: PacoMonkey-Build
          path: build/
